#ifndef PM6006_WEB_H
#define PM6006_WEB_H

#include <Arduino.h>

inline String buildPm6006Page() {
  return F(
    "<!DOCTYPE html><html><head>"
    "<meta charset='UTF-8'/>"
    "<meta name='viewport' content='width=device-width, initial-scale=1'/>"
    "<title>PM6006 Control</title>"
    "<style>"
    "body{font-family:sans-serif;background:#111;color:#eee;text-align:center;}"
    "h1{margin-top:20px;font-size:2em;}"
    ".status{position:fixed;top:10px;left:50%;transform:translateX(-50%);"
      "padding:10px 20px;background:rgba(0,0,0,0.8);border-radius:20px;"
      "font-weight:bold;transition:opacity 0.3s;z-index:1000;opacity:0;}"
    ".status.show{opacity:1;}"
    ".status.success{color:#4a4;background:rgba(74,170,74,0.2);}"
    ".status.error{color:#f44;background:rgba(244,68,68,0.2);}"
    ".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));"
      "gap:10px;margin:20px 20px 60px;max-width:800px;margin-left:auto;margin-right:auto;}"
    "button{padding:12px 8px;font-size:16px;border-radius:8px;border:none;"
      "cursor:pointer;background:#333;color:#eee;transition:0.1s;}"
    "button:hover{background:#555;transform:translateY(-1px);}"
    "button:active{background:#222;transform:translateY(0);}"
    "button:disabled{background:#222;color:#555;cursor:not-allowed;transform:none;opacity:0.6;}"
    ".power{background:#4a4;}button.power:hover{background:#5a5;}"
    ".poweroff{background:#a44;}button.poweroff:hover{background:#c55;}"
    "</style>"
    "</head><body>"
    "<div id='status' class='status'></div>"
    "<h1>🔊 Marantz PM6006</h1>"
    "<div class='grid'>"
    "<button class='power' onclick=\"send('PowerOn')\">⏻ ON</button>"
    "<button class='poweroff' onclick=\"send('PowerOff')\">⏹️ OFF</button>"
    "<button onclick=\"send('PowerToggle')\">⏻ Toggle</button>"
    "<button onclick=\"send('MuteToggle')\">🔇 Mute</button>"
    "<button onclick=\"send('VolumeUp')\">📈 Vol +</button>"
    "<button onclick=\"send('VolumeDown')\">📉 Vol -</button>"
    "<button onclick=\"send('InputPhono')\">🎛️ Phono</button>"
    "<button onclick=\"send('InputCD')\">💿 CD</button>"
    "<button onclick=\"send('InputNetwork')\">🌐 Network</button>"
    "<button onclick=\"send('InputTuner')\">📻 Tuner</button>"
    "<button disabled title='Code not found'>📼 Recorder</button>"
    "<button disabled title='Code not found'>🔌 Coaxial</button>"
    "<button onclick=\"send('InputOptical')\">🔦 Optical</button>"
    "<button disabled title='Code not found'>🎛️ Direct</button>"
    "</div>"
    "<p style='font-size:0.8em;color:#888;'>http://amp.local</p>"
    "<script>"
    "const statusEl=document.getElementById('status');"
    "function showStatus(msg,className){"
      "statusEl.textContent=msg;"
      "statusEl.className='status '+className;"
      "statusEl.classList.add('show');"
      "setTimeout(()=>statusEl.classList.remove('show'),2500);"
    "}"
    "function send(btn){"
      "showStatus('Sending '+btn+'...', '');"
      "fetch('/press',{"
        "method:'POST',"
        "headers:{'Content-Type':'application/x-www-form-urlencoded'},"
        "body:'btn='+encodeURIComponent(btn)"
      "})"
      ".then(r=>{"
        "if(!r.ok) throw new Error(r.statusText);"
        "return r.text();"
      "})"
      ".then(t=>{"
        "showStatus('✓ '+btn+' sent!', 'success');"
      "})"
      ".catch(e=>{"
        "showStatus('✗ '+btn+': '+e, 'error');"
      "});"
    "}"
    "</script>"
    "</body></html>"
  );
}

#endif // PM6006_WEB_H
